- name: Iterative Tasks Playbook
  hosts: all
  become: true

  tasks:
    - name: Copy files 10 times to the remote server
      copy:
        src: \\wsl.localhost\Ubuntu\home\acausley\week10
        dest: \\wsl.localhost\Ubuntu\home\acausley\week10
      with_sequence: start=1 end=10
      loop_control:
        loop_var: item

    - name: Change permissions to 644 on the copied files
      file:
        path: \\wsl.localhost\Ubuntu\home\acausley\week10
        mode: '0644'
      with_sequence: start=1 end=10
      loop_control:
        loop_var: item

    - name: Delete the 10 copied files
      file:
        path: \\wsl.localhost\Ubuntu\home\acausley\week10
        state: absent
      with_sequence: start=1 end=10
      loop_control:
        loop_var: item
