---
- name: Task Conditions Playbook
  hosts: all
  become: true

  tasks:
    - name: Install Apache on Debian-based systems
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Apache on RedHat-based systems
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Copy a sample file to the remote home directory if it doesn't exist
      copy:
        src: \\wsl.localhost\Ubuntu\home\acausley\samplefile.txt
        dest: "{{ ansible_user_dir }}/samplefile.txt"
        force: no
      when: ansible_facts['os_family'] in ['Debian', 'RedHat']

    - name: Reboot the system if running Alma Linux
      reboot:
        reboot_timeout: 600
        test_command: whoami
      when: ansible_facts['distribution'] == 'AlmaLinux'

    - name: Create a new directory if it doesn't exist
      file:
        path: \\wsl.localhost\Ubuntu\home\acausley\week10
        state: directory
      when: not ansible_facts['ansible_facts']['ansible_facts']['ansible_os_family'] in ['directory']

    - name: Delete the sample file if OS is RedHat-based and IP address contains 10.2.37.X
      file:
        path: "{{ ansible_user_dir }}/samplefile.txt"
        state: absent
      when: 
        - ansible_facts['os_family'] == 'RedHat'
        - ansible_facts['ansible_default_ipv4']['address'] | regex_search('^10\.2\.37\.[1-9][0-9]?$')

    - name: Block to handle errors and continue
      block:
        - name: Simulate a task that could fail
          command: /bin/false 
      rescue:
        - name: Log the error but continue
          debug:
            msg: "This task failed, but the playbook will continue"
